# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-30 11:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='subjects',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
